---
title: "Installation des logiciels nécessaires"
subtitle: "Atelier Sageo, Québec, Juin 2023"
author: "Timothée Giraud, Nicolas Lambert, Matthieu Viry, Ronan Ysebaert (UAR RIATE, CNRS, Université Paris Cité)"
format:
  html:
    theme: sandstone
    fontsize: 0.9em
    code-tools: true
    embed-resources: true
    toc: true
    toc-depth: 3
    linkcolor: "#8631ad"
execute: 
  cache: false
---

Afin de suivre l'atelier, il est nécessaire de disposer des logiciels suivants :

- [R](https://www.r-project.org/)
- [RStudio](https://posit.co/download/rstudio-desktop/)
- [Python](https://www.python.org/)
- [Quarto](https://quarto.org/) (RStudio inclus Quarto depuis la version *2022.07*)
- Plusieurs packages R et Python

Au cours de l'atelier, une fois les instructions d'installation effectuées, toutes les manipulations nécessaires à la production d'un document avec Quarto seront réalisées directement depuis l'IDE RStudio.

# Windows 10 / Windows 11

### Installation de R

- Se rendre à l'URL [https://cran.r-project.org/bin/windows/base/](https://cran.r-project.org/bin/windows/base/)
- Cliquer sur *"Download R-4.3.0 for Windows"* pour télécharger l'installeur sur votre ordinateur
- Exécutez l'installeur - aller jusqu'au bout de l'installeur en laissant les options par défaut

### Installation RStudio

- Télécharger l'installeur de RStudio à partir de ce lien : [https://download1.rstudio.org/electron/windows/RStudio-2023.03.1-446.exe](https://download1.rstudio.org/electron/windows/RStudio-2023.03.1-446.exe)
- Exécutez l'installeur - aller jusqu'au bout de l'installeur en laissant les options par défaut


### Installation de Python

- Télécharger le fichier [https://www.python.org/ftp/python/3.11.3/python-3.11.3-amd64.exe](https://www.python.org/ftp/python/3.11.3/python-3.11.3-amd64.exe)
- L'exécuter et cocher l'option *"Add python.exe to PATH"* puis cliquer sur *"Install Now"*
- À la fin de l'installation, il est suggéré de changer la limite de longueur des noms de fichiers, ceci est souhaitable, cliquez donc sur *"Disable path length limit"*
- Fermer l'installeur

### Installation des dépendances Python requises

- Ouvrir l'interpréteur de commande du système (appuyer sur la touche "windows" puis saisir CMD dans la barre de recherche et ouvrir l'application "Invite de commandes" qui est proposée)
- Créer un envrionnement virtuel :

```powershell
python -m venv env-quarto
```

- Activer l'environnement virtuel tout juste créé :

```powershell
.\env-quarto\Scripts\activate.bat
```

- Installer les dépendances Python requises :

```powershell
python -m pip install numpy geopandas rasterio rasterstats matplotlib rioxarray netCDF4 scipy
```

- Fermer le terminal

### Installation des dépendances R requises

- Ouvrir RStudio et saisir la commande suivante dans l'interpréteur R :

```r
install.packages(c('markdown', 'rmarkdown', 'reticulate', 'sf', 'readxl', 'mapsf', 'osmdata', 'maptiles', 'tanaka', 'spatstat', 'terra'))
```

### Vous disposez de tout le nécessaire pour l'atelier !

Les instructions pour utiliser l'environnement virtuel Python créé depuis RStudio et depuis votre document Quarto vous seront fournies lors de l'atelier.

# Linux (Ubuntu 22)

### Installation / mise-à-jour de R et des dépendances pour RStudio et les différents packages R

- Ajouter le dépôt de paquets logiciels (PPA) du CRAN pour obtenir R dans sa dernière version qui n'est pas proposée par défaut par Ubuntu (il s'agit des instructions issues de la page [https://cloud.r-project.org/bin/linux/ubuntu/](https://cloud.r-project.org/bin/linux/ubuntu/)).

```bash
# update indices
sudo apt update -qq
# install two helper packages we need
sudo apt install --no-install-recommends software-properties-common dirmngr
# add the signing key (by Michael Rutter) for these repos
# To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 
# Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
# add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
```

- Si vous avez déjà R, pour mettre à jour vers la dernière version :

```bash
sudo apt update && sudo apt upgrade
```

- Sinon pour installer R :

```bash
sudo apt install r-base
```

- Pour installer les dépendances nécessaires pour RStudio et pour les packages R qui seront installés par la suite :

```bash
sudo apt install libssl-dev libpq5 libclang-dev curl \
  libudunits2-dev libgdal-dev libgeos-dev libproj-dev \
  libcurl4-openssl-dev libxml2-dev libpng-dev libfontconfig1-dev
```

### Installation de RStudio

```bash
curl https://download1.rstudio.org/electron/jammy/amd64/rstudio-2023.03.1-446-amd64.deb --output rstudio-2023.03.1-446-amd64.deb
sudo dpkg -i rstudio-2023.03.1-446-amd64.deb
```

### Utilisation de la version de Python livrée avec le système et création d'un environnement virtuel

- Ouvrir un terminal

- Saisir les commandes suivantes :

```bash
sudo apt install python3-venv
python3 -m venv env-quarto
source env-quarto/bin/activate
python -m pip install numpy geopandas rasterio rasterstats matplotlib rioxarray netCDF4 scipy
```

- Fermer le terminal

### Installation des dépendances R requises 

- Ouvrir RStudio et saisir la commande suivante dans l'interpréteur R :

```r
install.packages(c('markdown', 'rmarkdown', 'reticulate', 'sf', 'readxl', 'mapsf', 'osmdata', 'maptiles', 'tanaka', 'spatstat', 'terra'))
```

### Vous disposez de tout le nécessaire pour l'atelier !

Les instructions pour utiliser l'environnement virtuel Python créé depuis RStudio et depuis votre document Quarto vous seront fournies lors de l'atelier.


# Mac OS X

### Installation de R

- Se rendre à l'URL [https://cran.r-project.org/bin/macosx/](https://cran.r-project.org/bin/macosx/)
- Selon votre machine, télécharger l'installeur approprié en cliquant sur :
  * R-4.3.0-arm64.pkg
  * R-4.3.0-x86_64.pkg
- Exécutez l'installeur - aller jusqu'au bout de l'installeur en laissant les options par défaut

### Installation de RStudio

- Télécharger l'installeur à partir de ce lien : [https://download1.rstudio.org/electron/macos/RStudio-2023.03.1-446.dmg](https://download1.rstudio.org/electron/macos/RStudio-2023.03.1-446.dmg)
- L'exécuter et aller jusqu'au bout de l'installeur en laissant les options par défaut


### Installation de Python

- Télécharger le fichier [https://www.python.org/ftp/python/3.11.3/python-3.11.3-macos11.pkg](https://www.python.org/ftp/python/3.11.3/python-3.11.3-macos11.pkg)
- L'exécuter et aller jusqu'au bout de l'installeur en laissant les options par défaut

### Installation des dépendances Python requises

- Ouvrir un terminal système (soit depuis *Finder*, ouvrir le dossier /Application/Utilitaires et cliquer deux fois sur *Terminal*, soit depuis l'icone *Launchpad* dans le Dock, saisir "Terminal" dans le champ de recherche, puis cliquer sur *Terminal*)

- Créer un envrionnement virtuel :

```sh
python3 -m venv env-quarto
```

- Activer l'environnement virtuel tout juste créé :

```sh
source env-quarto/bin/activate
```

- Installer les dépendances Python requises :

```sh
python -m pip install numpy geopandas rasterio rasterstats matplotlib rioxarray netCDF4 scipy
```

- Fermer le terminal

### Installation des dépendances R requises

- Ouvrir RStudio et saisir la commande suivante dans l'interpréteur R :

```r
install.packages(c('markdown', 'rmarkdown', 'reticulate', 'sf', 'readxl', 'mapsf', 'osmdata', 'maptiles', 'tanaka', 'spatstat', 'terra'))
```

### Vous disposez de tout le nécessaire pour l'atelier !

Les instructions pour utiliser l'environnement virtuel Python créé depuis RStudio et depuis votre document Quarto vous seront fournies lors de l'atelier.

# En cas d'erreur lors de l'installation...

*__... ou si besoin d'aide à l'installation des outils nécessaires à l'atelier sur un autre système d'exploitation que ceux cités dans ce document__ * : n'hésitez pas à nous contacter : ([matthieu.viry@cnrs.fr](mailto:matthieu.viry@cnrs.fr)).